/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsPeriod {
    #[serde(rename = "date_from", skip_serializing_if = "Option::is_none")]
    pub date_from: Option<String>,
    #[serde(rename = "date_to", skip_serializing_if = "Option::is_none")]
    pub date_to: Option<String>,
    #[serde(rename = "additional_fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub additional_fields: Option<Option<serde_json::Value>>,
    #[serde(rename = "custom_fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Option<serde_json::Value>>,
}

impl AnalyticsPeriod {
    pub fn new() -> AnalyticsPeriod {
        AnalyticsPeriod {
            date_from: None,
            date_to: None,
            additional_fields: None,
            custom_fields: None,
        }
    }
}

