/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoryDeleteBatch {
    /// Contains an array of category IDs to delete.
    #[serde(rename = "payload")]
    pub payload: Vec<models::CategoryDeleteBatchPayloadInner>,
}

impl CategoryDeleteBatch {
    pub fn new(payload: Vec<models::CategoryDeleteBatchPayloadInner>) -> CategoryDeleteBatch {
        CategoryDeleteBatch {
            payload,
        }
    }
}

