/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerAdd {
    /// Defines customer's email
    #[serde(rename = "email")]
    pub email: String,
    /// Defines customer's first name
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Defines customer's last name
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Defines customer's unique password
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Defines the group where the customer
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// Customer group_id
    #[serde(rename = "group_id", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    /// Groups that will be assigned to a customer
    #[serde(rename = "group_ids", skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<String>,
    /// Defines customer's status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Entity's date creation
    #[serde(rename = "created_time", skip_serializing_if = "Option::is_none")]
    pub created_time: Option<String>,
    /// Entity's date modification
    #[serde(rename = "modified_time", skip_serializing_if = "Option::is_none")]
    pub modified_time: Option<String>,
    /// Specifies customer's login name
    #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
    pub login: Option<String>,
    /// Defines customer's last login time
    #[serde(rename = "last_login", skip_serializing_if = "Option::is_none")]
    pub last_login: Option<String>,
    /// Defines customer's birthday
    #[serde(rename = "birth_day", skip_serializing_if = "Option::is_none")]
    pub birth_day: Option<String>,
    /// Defines whether the newsletter subscription is available for the user
    #[serde(rename = "news_letter_subscription", skip_serializing_if = "Option::is_none")]
    pub news_letter_subscription: Option<bool>,
    /// Defines consents to notifications
    #[serde(rename = "consents", skip_serializing_if = "Option::is_none")]
    pub consents: Option<Vec<models::CustomerAddConsentsInner>>,
    /// Defines customer's gender
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    /// Link to customer website
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// Defines customer's fax
    #[serde(rename = "fax", skip_serializing_if = "Option::is_none")]
    pub fax: Option<String>,
    /// Defines customer's company
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<String>,
    /// Defines customer's phone number
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// The customer note.
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// Specifies ISO code or name of country
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Store Id
    #[serde(rename = "store_id", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Vec<models::CustomerAddAddressInner>>,
}

impl CustomerAdd {
    pub fn new(email: String) -> CustomerAdd {
        CustomerAdd {
            email,
            first_name: None,
            last_name: None,
            password: None,
            group: None,
            group_id: None,
            group_ids: None,
            status: None,
            created_time: None,
            modified_time: None,
            login: None,
            last_login: None,
            birth_day: None,
            news_letter_subscription: None,
            consents: None,
            gender: None,
            website: None,
            fax: None,
            company: None,
            phone: None,
            note: None,
            country: None,
            store_id: None,
            address: None,
        }
    }
}

