/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerAddAddressInner {
    /// Specifies customer's address type
    #[serde(rename = "address_book_type", skip_serializing_if = "Option::is_none")]
    pub address_book_type: Option<String>,
    /// Specifies customer's first name in the address book
    #[serde(rename = "address_book_first_name", skip_serializing_if = "Option::is_none")]
    pub address_book_first_name: Option<String>,
    /// Specifies customer's last name in the address book
    #[serde(rename = "address_book_last_name", skip_serializing_if = "Option::is_none")]
    pub address_book_last_name: Option<String>,
    /// Specifies customer's company name in the address book
    #[serde(rename = "address_book_company", skip_serializing_if = "Option::is_none")]
    pub address_book_company: Option<String>,
    /// Specifies customer's fax in the address book
    #[serde(rename = "address_book_fax", skip_serializing_if = "Option::is_none")]
    pub address_book_fax: Option<String>,
    /// Specifies customer's phone number in the address book
    #[serde(rename = "address_book_phone", skip_serializing_if = "Option::is_none")]
    pub address_book_phone: Option<String>,
    /// Specifies customer's mobile phone number in the address book
    #[serde(rename = "address_book_phone_mobile", skip_serializing_if = "Option::is_none")]
    pub address_book_phone_mobile: Option<String>,
    /// Specifies customer's website in the address book
    #[serde(rename = "address_book_website", skip_serializing_if = "Option::is_none")]
    pub address_book_website: Option<String>,
    /// Specifies customer's first address in the address book
    #[serde(rename = "address_book_address1", skip_serializing_if = "Option::is_none")]
    pub address_book_address1: Option<String>,
    /// Specifies customer's second address in the address book
    #[serde(rename = "address_book_address2", skip_serializing_if = "Option::is_none")]
    pub address_book_address2: Option<String>,
    /// Specifies customer's city in the address book
    #[serde(rename = "address_book_city", skip_serializing_if = "Option::is_none")]
    pub address_book_city: Option<String>,
    /// ISO code or name of country
    #[serde(rename = "address_book_country", skip_serializing_if = "Option::is_none")]
    pub address_book_country: Option<String>,
    /// ISO code or name of state.
    #[serde(rename = "address_book_state", skip_serializing_if = "Option::is_none")]
    pub address_book_state: Option<String>,
    /// Specifies customer's postcode
    #[serde(rename = "address_book_postcode", skip_serializing_if = "Option::is_none")]
    pub address_book_postcode: Option<String>,
    /// Specifies customer's gender
    #[serde(rename = "address_book_gender", skip_serializing_if = "Option::is_none")]
    pub address_book_gender: Option<String>,
    /// Specifies customer's region
    #[serde(rename = "address_book_region", skip_serializing_if = "Option::is_none")]
    pub address_book_region: Option<String>,
    /// Defines whether the address is used by default
    #[serde(rename = "address_book_default", skip_serializing_if = "Option::is_none")]
    pub address_book_default: Option<bool>,
    /// Add Tax Id
    #[serde(rename = "address_book_tax_id", skip_serializing_if = "Option::is_none")]
    pub address_book_tax_id: Option<String>,
    /// The national ID card number of this person, or a unique tax identification number.
    #[serde(rename = "address_book_identification_number", skip_serializing_if = "Option::is_none")]
    pub address_book_identification_number: Option<String>,
    /// Specifies customer's alias in the address book
    #[serde(rename = "address_book_alias", skip_serializing_if = "Option::is_none")]
    pub address_book_alias: Option<String>,
}

impl CustomerAddAddressInner {
    pub fn new() -> CustomerAddAddressInner {
        CustomerAddAddressInner {
            address_book_type: None,
            address_book_first_name: None,
            address_book_last_name: None,
            address_book_company: None,
            address_book_fax: None,
            address_book_phone: None,
            address_book_phone_mobile: None,
            address_book_website: None,
            address_book_address1: None,
            address_book_address2: None,
            address_book_city: None,
            address_book_country: None,
            address_book_state: None,
            address_book_postcode: None,
            address_book_gender: None,
            address_book_region: None,
            address_book_default: None,
            address_book_tax_id: None,
            address_book_identification_number: None,
            address_book_alias: None,
        }
    }
}

