/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerAddConsentsInner {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "opt_in_level")]
    pub opt_in_level: String,
}

impl CustomerAddConsentsInner {
    pub fn new(r#type: Type, status: String, opt_in_level: String) -> CustomerAddConsentsInner {
        CustomerAddConsentsInner {
            r#type,
            status,
            opt_in_level,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "sms")]
    Sms,
}

impl Default for Type {
    fn default() -> Type {
        Self::Email
    }
}

