/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelResponseTaxClassInfo {
    #[serde(rename = "return_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub return_code: Option<Option<i32>>,
    #[serde(rename = "return_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub return_message: Option<Option<String>>,
    #[serde(rename = "result", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub result: Option<Option<Box<models::ResponseTaxClassInfoResult>>>,
    #[serde(rename = "additional_fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub additional_fields: Option<Option<serde_json::Value>>,
    #[serde(rename = "custom_fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Option<serde_json::Value>>,
}

impl ModelResponseTaxClassInfo {
    pub fn new() -> ModelResponseTaxClassInfo {
        ModelResponseTaxClassInfo {
            return_code: None,
            return_message: None,
            result: None,
            additional_fields: None,
            custom_fields: None,
        }
    }
}

