/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderCalculateBundle {
    #[serde(rename = "product_id", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    #[serde(rename = "sku", skip_serializing_if = "Option::is_none")]
    pub sku: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(rename = "price_inc_tax", skip_serializing_if = "Option::is_none")]
    pub price_inc_tax: Option<f64>,
    #[serde(rename = "tax_rate", skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<f64>,
    #[serde(rename = "unit_discount", skip_serializing_if = "Option::is_none")]
    pub unit_discount: Option<f64>,
    #[serde(rename = "weight", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weight: Option<Option<f64>>,
    #[serde(rename = "weight_unit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weight_unit: Option<Option<String>>,
    #[serde(rename = "barcode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub barcode: Option<Option<String>>,
    #[serde(rename = "variant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variant_id: Option<Option<String>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::OrderItemOption>>,
    #[serde(rename = "additional_fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub additional_fields: Option<Option<serde_json::Value>>,
    #[serde(rename = "custom_fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Option<serde_json::Value>>,
}

impl OrderCalculateBundle {
    pub fn new() -> OrderCalculateBundle {
        OrderCalculateBundle {
            product_id: None,
            sku: None,
            name: None,
            quantity: None,
            price: None,
            price_inc_tax: None,
            tax_rate: None,
            unit_discount: None,
            weight: None,
            weight_unit: None,
            barcode: None,
            variant_id: None,
            options: None,
            additional_fields: None,
            custom_fields: None,
        }
    }
}

