/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderCalculateOrderItemInner {
    /// Defines orders specified by order item id
    #[serde(rename = "order_item_id")]
    pub order_item_id: String,
    /// Defines orders specified by order item quantity
    #[serde(rename = "order_item_quantity")]
    pub order_item_quantity: i32,
    /// Ordered product variant. Where x is order item ID
    #[serde(rename = "order_item_variant_id", skip_serializing_if = "Option::is_none")]
    pub order_item_variant_id: Option<String>,
    /// Index of the parent grouped/bundle product
    #[serde(rename = "order_item_parent", skip_serializing_if = "Option::is_none")]
    pub order_item_parent: Option<i32>,
    /// Option name of the parent grouped/bundle product
    #[serde(rename = "order_item_parent_option_name", skip_serializing_if = "Option::is_none")]
    pub order_item_parent_option_name: Option<String>,
    #[serde(rename = "order_item_option", skip_serializing_if = "Option::is_none")]
    pub order_item_option: Option<Vec<models::OrderCalculateOrderItemInnerOrderItemOptionInner>>,
}

impl OrderCalculateOrderItemInner {
    pub fn new(order_item_id: String, order_item_quantity: i32) -> OrderCalculateOrderItemInner {
        OrderCalculateOrderItemInner {
            order_item_id,
            order_item_quantity,
            order_item_variant_id: None,
            order_item_parent: None,
            order_item_parent_option_name: None,
            order_item_option: None,
        }
    }
}

