/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner {
    /// Ordered Product Option Name. Where x is order item ID, y is order item option ID
    #[serde(rename = "order_item_option_name", skip_serializing_if = "Option::is_none")]
    pub order_item_option_name: Option<String>,
    /// Product Option ID. Where x is order item ID, y is order item option ID
    #[serde(rename = "order_item_option_id", skip_serializing_if = "Option::is_none")]
    pub order_item_option_id: Option<String>,
    /// Ordered product option value Where x is order item ID, y - order item option ID
    #[serde(rename = "order_item_option_value", skip_serializing_if = "Option::is_none")]
    pub order_item_option_value: Option<String>,
    /// Product option value ID, where x is order item ID, y - order item option ID
    #[serde(rename = "order_item_option_value_id", skip_serializing_if = "Option::is_none")]
    pub order_item_option_value_id: Option<String>,
    /// Product option used in combinations flag, where x is order item ID, y - order item option ID
    #[serde(rename = "order_item_option_used_in_combinations", skip_serializing_if = "Option::is_none")]
    pub order_item_option_used_in_combinations: Option<bool>,
}

impl OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner {
    pub fn new() -> OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner {
        OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner {
            order_item_option_name: None,
            order_item_option_id: None,
            order_item_option_value: None,
            order_item_option_value_id: None,
            order_item_option_used_in_combinations: None,
        }
    }
}

