/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderShipmentAdd {
    /// Defines the order for which the shipment will be created
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    /// This parameter is used for selecting a warehouse where you need to set/modify a product quantity.
    #[serde(rename = "warehouse_id", skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<String>,
    /// Store Id
    #[serde(rename = "store_id", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    /// Defines company name that provide tracking of shipment
    #[serde(rename = "shipment_provider", skip_serializing_if = "Option::is_none")]
    pub shipment_provider: Option<String>,
    /// Define shipping method
    #[serde(rename = "shipping_method", skip_serializing_if = "Option::is_none")]
    pub shipping_method: Option<String>,
    /// Defines items in the order that will be shipped
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::OrderShipmentAddItemsInner>>,
    /// Defines shipment's tracking numbers that have to be added</br> How set tracking numbers to appropriate carrier:<ul><li>tracking_numbers[]=a2c.demo1,a2c.demo2 - set default carrier</li><li>tracking_numbers[<b>carrier_id</b>]=a2c.demo - set appropriate carrier</li></ul>To get the list of carriers IDs that are available in your store, use the <a href = \"https://api2cart.com/docs/#/cart/CartInfo\">cart.info</a > method
    #[serde(rename = "tracking_numbers", skip_serializing_if = "Option::is_none")]
    pub tracking_numbers: Option<Vec<models::OrderShipmentAddTrackingNumbersInner>>,
    /// Defines custom tracking link
    #[serde(rename = "tracking_link", skip_serializing_if = "Option::is_none")]
    pub tracking_link: Option<String>,
    /// Defines shipment's status
    #[serde(rename = "is_shipped", skip_serializing_if = "Option::is_none")]
    pub is_shipped: Option<bool>,
    /// Send notifications to customer after shipment was created
    #[serde(rename = "send_notifications", skip_serializing_if = "Option::is_none")]
    pub send_notifications: Option<bool>,
    /// This parameter is used for adjust stock.
    #[serde(rename = "adjust_stock", skip_serializing_if = "Option::is_none")]
    pub adjust_stock: Option<bool>,
    /// If the value is 'true' and order exist in our cache, we will use order.info from cache to prepare shipment items.
    #[serde(rename = "enable_cache", skip_serializing_if = "Option::is_none")]
    pub enable_cache: Option<bool>,
    /// Disable or enable check process status. Please note that the response will be slower due to additional requests to the store.
    #[serde(rename = "check_process_status", skip_serializing_if = "Option::is_none")]
    pub check_process_status: Option<bool>,
    /// Defines name of the company which provides shipment tracking
    #[serde(rename = "tracking_provider", skip_serializing_if = "Option::is_none")]
    pub tracking_provider: Option<String>,
    /// Use the latest platform API version
    #[serde(rename = "use_latest_api_version", skip_serializing_if = "Option::is_none")]
    pub use_latest_api_version: Option<bool>,
    /// A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong>
    #[serde(rename = "idempotency_key", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
}

impl OrderShipmentAdd {
    pub fn new() -> OrderShipmentAdd {
        OrderShipmentAdd {
            order_id: None,
            warehouse_id: None,
            store_id: None,
            shipment_provider: None,
            shipping_method: None,
            items: None,
            tracking_numbers: None,
            tracking_link: None,
            is_shipped: None,
            send_notifications: None,
            adjust_stock: None,
            enable_cache: None,
            check_process_status: None,
            tracking_provider: None,
            use_latest_api_version: None,
            idempotency_key: None,
        }
    }
}

