/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductVariantDeleteBatchPayloadInner {
    #[serde(rename = "product_id")]
    pub product_id: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "store_id", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
}

impl ProductVariantDeleteBatchPayloadInner {
    pub fn new(product_id: String, id: String) -> ProductVariantDeleteBatchPayloadInner {
        ProductVariantDeleteBatchPayloadInner {
            product_id,
            id,
            store_id: None,
        }
    }
}

