/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductAddSpecificsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
    #[serde(rename = "used_for_variations", skip_serializing_if = "Option::is_none")]
    pub used_for_variations: Option<bool>,
    #[serde(rename = "scale_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scale_id: Option<Option<i32>>,
    #[serde(rename = "food_details", skip_serializing_if = "Option::is_none")]
    pub food_details: Option<Box<models::ProductAddSpecificsInnerFoodDetails>>,
    #[serde(rename = "group_products_details", skip_serializing_if = "Option::is_none")]
    pub group_products_details: Option<Vec<models::ProductAddSpecificsInnerGroupProductsDetailsInner>>,
    #[serde(rename = "booking_details", skip_serializing_if = "Option::is_none")]
    pub booking_details: Option<Box<models::ProductAddSpecificsInnerBookingDetails>>,
}

impl ProductAddSpecificsInner {
    pub fn new() -> ProductAddSpecificsInner {
        ProductAddSpecificsInner {
            name: None,
            value: None,
            values: None,
            used_for_variations: None,
            scale_id: None,
            food_details: None,
            group_products_details: None,
            booking_details: None,
        }
    }
}

