/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Product {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "u_model", skip_serializing_if = "Option::is_none")]
    pub u_model: Option<String>,
    #[serde(rename = "u_sku", skip_serializing_if = "Option::is_none")]
    pub u_sku: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "short_description", skip_serializing_if = "Option::is_none")]
    pub short_description: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(rename = "advanced_price", skip_serializing_if = "Option::is_none")]
    pub advanced_price: Option<Vec<models::ProductAdvancedPrice>>,
    #[serde(rename = "cost_price", skip_serializing_if = "Option::is_none")]
    pub cost_price: Option<f64>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    #[serde(rename = "inventory", skip_serializing_if = "Option::is_none")]
    pub inventory: Option<Vec<models::ProductInventory>>,
    #[serde(rename = "group_items", skip_serializing_if = "Option::is_none")]
    pub group_items: Option<Vec<models::ProductGroupItem>>,
    #[serde(rename = "u_brand_id", skip_serializing_if = "Option::is_none")]
    pub u_brand_id: Option<String>,
    #[serde(rename = "u_brand", skip_serializing_if = "Option::is_none")]
    pub u_brand: Option<String>,
    #[serde(rename = "categories_ids", skip_serializing_if = "Option::is_none")]
    pub categories_ids: Option<Vec<String>>,
    #[serde(rename = "stores_ids", skip_serializing_if = "Option::is_none")]
    pub stores_ids: Option<Vec<String>>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "seo_url", skip_serializing_if = "Option::is_none")]
    pub seo_url: Option<String>,
    #[serde(rename = "meta_title", skip_serializing_if = "Option::is_none")]
    pub meta_title: Option<String>,
    #[serde(rename = "meta_keywords", skip_serializing_if = "Option::is_none")]
    pub meta_keywords: Option<String>,
    #[serde(rename = "meta_description", skip_serializing_if = "Option::is_none")]
    pub meta_description: Option<String>,
    #[serde(rename = "avail_sale", skip_serializing_if = "Option::is_none")]
    pub avail_sale: Option<bool>,
    #[serde(rename = "avail_view", skip_serializing_if = "Option::is_none")]
    pub avail_view: Option<bool>,
    #[serde(rename = "is_virtual", skip_serializing_if = "Option::is_none")]
    pub is_virtual: Option<bool>,
    #[serde(rename = "is_downloadable", skip_serializing_if = "Option::is_none")]
    pub is_downloadable: Option<bool>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    #[serde(rename = "weight_unit", skip_serializing_if = "Option::is_none")]
    pub weight_unit: Option<String>,
    #[serde(rename = "sort_order", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<i32>,
    #[serde(rename = "in_stock", skip_serializing_if = "Option::is_none")]
    pub in_stock: Option<bool>,
    #[serde(rename = "on_sale", skip_serializing_if = "Option::is_none")]
    pub on_sale: Option<bool>,
    #[serde(rename = "backorders", skip_serializing_if = "Option::is_none")]
    pub backorders: Option<String>,
    #[serde(rename = "manage_stock", skip_serializing_if = "Option::is_none")]
    pub manage_stock: Option<String>,
    #[serde(rename = "is_stock_managed", skip_serializing_if = "Option::is_none")]
    pub is_stock_managed: Option<bool>,
    #[serde(rename = "create_at", skip_serializing_if = "Option::is_none")]
    pub create_at: Option<Box<models::A2CDateTime>>,
    #[serde(rename = "modified_at", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<Box<models::A2CDateTime>>,
    #[serde(rename = "tax_class_id", skip_serializing_if = "Option::is_none")]
    pub tax_class_id: Option<String>,
    #[serde(rename = "special_price", skip_serializing_if = "Option::is_none")]
    pub special_price: Option<Box<models::SpecialPrice>>,
    #[serde(rename = "tier_price", skip_serializing_if = "Option::is_none")]
    pub tier_price: Option<Vec<models::ProductTierPrice>>,
    #[serde(rename = "group_price", skip_serializing_if = "Option::is_none")]
    pub group_price: Option<Vec<models::ProductGroupPrice>>,
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<models::Image>>,
    #[serde(rename = "product_options", skip_serializing_if = "Option::is_none")]
    pub product_options: Option<Vec<models::ProductOption>>,
    #[serde(rename = "u_upc", skip_serializing_if = "Option::is_none")]
    pub u_upc: Option<String>,
    #[serde(rename = "u_mpn", skip_serializing_if = "Option::is_none")]
    pub u_mpn: Option<String>,
    #[serde(rename = "u_gtin", skip_serializing_if = "Option::is_none")]
    pub u_gtin: Option<String>,
    #[serde(rename = "u_isbn", skip_serializing_if = "Option::is_none")]
    pub u_isbn: Option<String>,
    #[serde(rename = "u_ean", skip_serializing_if = "Option::is_none")]
    pub u_ean: Option<String>,
    #[serde(rename = "related_products_ids", skip_serializing_if = "Option::is_none")]
    pub related_products_ids: Option<Vec<String>>,
    #[serde(rename = "up_sell_products_ids", skip_serializing_if = "Option::is_none")]
    pub up_sell_products_ids: Option<Vec<String>>,
    #[serde(rename = "cross_sell_products_ids", skip_serializing_if = "Option::is_none")]
    pub cross_sell_products_ids: Option<Vec<String>>,
    #[serde(rename = "dimensions_unit", skip_serializing_if = "Option::is_none")]
    pub dimensions_unit: Option<String>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<f64>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<f64>,
    #[serde(rename = "discounts", skip_serializing_if = "Option::is_none")]
    pub discounts: Option<Vec<models::Discount>>,
    #[serde(rename = "additional_fields", skip_serializing_if = "Option::is_none")]
    pub additional_fields: Option<serde_json::Value>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<serde_json::Value>,
}

impl Product {
    pub fn new() -> Product {
        Product {
            id: None,
            r#type: None,
            u_model: None,
            u_sku: None,
            name: None,
            description: None,
            short_description: None,
            price: None,
            advanced_price: None,
            cost_price: None,
            quantity: None,
            inventory: None,
            group_items: None,
            u_brand_id: None,
            u_brand: None,
            categories_ids: None,
            stores_ids: None,
            url: None,
            seo_url: None,
            meta_title: None,
            meta_keywords: None,
            meta_description: None,
            avail_sale: None,
            avail_view: None,
            is_virtual: None,
            is_downloadable: None,
            weight: None,
            weight_unit: None,
            sort_order: None,
            in_stock: None,
            on_sale: None,
            backorders: None,
            manage_stock: None,
            is_stock_managed: None,
            create_at: None,
            modified_at: None,
            tax_class_id: None,
            special_price: None,
            tier_price: None,
            group_price: None,
            images: None,
            product_options: None,
            u_upc: None,
            u_mpn: None,
            u_gtin: None,
            u_isbn: None,
            u_ean: None,
            related_products_ids: None,
            up_sell_products_ids: None,
            cross_sell_products_ids: None,
            dimensions_unit: None,
            width: None,
            height: None,
            length: None,
            discounts: None,
            additional_fields: None,
            custom_fields: None,
        }
    }
}

