/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductTaxAdd {
    /// Defines products specified by product id
    #[serde(rename = "product_id", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    /// Defines tax class name where tax has to be added
    #[serde(rename = "name")]
    pub name: String,
    /// Defines tax rates of specified tax classes
    #[serde(rename = "tax_rates")]
    pub tax_rates: Vec<models::ProductTaxAddTaxRatesInner>,
    /// A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong>
    #[serde(rename = "idempotency_key", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
}

impl ProductTaxAdd {
    pub fn new(name: String, tax_rates: Vec<models::ProductTaxAddTaxRatesInner>) -> ProductTaxAdd {
        ProductTaxAdd {
            product_id: None,
            name,
            tax_rates,
            idempotency_key: None,
        }
    }
}

