/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductAddShippingDetailsInner {
    #[serde(rename = "shipping_type", skip_serializing_if = "Option::is_none")]
    pub shipping_type: Option<String>,
    #[serde(rename = "shipping_service", skip_serializing_if = "Option::is_none")]
    pub shipping_service: Option<String>,
    #[serde(rename = "shipping_cost", skip_serializing_if = "Option::is_none")]
    pub shipping_cost: Option<f64>,
}

impl ProductAddShippingDetailsInner {
    pub fn new() -> ProductAddShippingDetailsInner {
        ProductAddShippingDetailsInner {
            shipping_type: None,
            shipping_service: None,
            shipping_cost: None,
        }
    }
}

