/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductVariantUpdateBatchPayloadInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "product_id")]
    pub product_id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "short_description", skip_serializing_if = "Option::is_none")]
    pub short_description: Option<String>,
    #[serde(rename = "sku", skip_serializing_if = "Option::is_none")]
    pub sku: Option<String>,
    #[serde(rename = "upc", skip_serializing_if = "Option::is_none")]
    pub upc: Option<String>,
    #[serde(rename = "mpn", skip_serializing_if = "Option::is_none")]
    pub mpn: Option<String>,
    #[serde(rename = "gtin", skip_serializing_if = "Option::is_none")]
    pub gtin: Option<String>,
    #[serde(rename = "isbn", skip_serializing_if = "Option::is_none")]
    pub isbn: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(rename = "special_price", skip_serializing_if = "Option::is_none")]
    pub special_price: Option<f64>,
    #[serde(rename = "cost_price", skip_serializing_if = "Option::is_none")]
    pub cost_price: Option<f64>,
    #[serde(rename = "retail_price", skip_serializing_if = "Option::is_none")]
    pub retail_price: Option<f64>,
    /// If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    #[serde(rename = "advanced_prices", skip_serializing_if = "Option::is_none")]
    pub advanced_prices: Option<Vec<models::ProductUpdateBatchPayloadInnerAdvancedPricesInner>>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    #[serde(rename = "reserve_quantity", skip_serializing_if = "Option::is_none")]
    pub reserve_quantity: Option<f64>,
    #[serde(rename = "increase_quantity", skip_serializing_if = "Option::is_none")]
    pub increase_quantity: Option<f64>,
    #[serde(rename = "reduce_quantity", skip_serializing_if = "Option::is_none")]
    pub reduce_quantity: Option<f64>,
    #[serde(rename = "warehouse_id", skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<String>,
    #[serde(rename = "manufacturer_id", skip_serializing_if = "Option::is_none")]
    pub manufacturer_id: Option<String>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<f64>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<f64>,
    #[serde(rename = "store_id", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    #[serde(rename = "lang_id", skip_serializing_if = "Option::is_none")]
    pub lang_id: Option<String>,
    #[serde(rename = "tax_class_id", skip_serializing_if = "Option::is_none")]
    pub tax_class_id: Option<String>,
    #[serde(rename = "backorder_status", skip_serializing_if = "Option::is_none")]
    pub backorder_status: Option<String>,
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<String>,
    #[serde(rename = "is_default", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    #[serde(rename = "in_stock", skip_serializing_if = "Option::is_none")]
    pub in_stock: Option<bool>,
    #[serde(rename = "is_virtual", skip_serializing_if = "Option::is_none")]
    pub is_virtual: Option<bool>,
    #[serde(rename = "downloadable", skip_serializing_if = "Option::is_none")]
    pub downloadable: Option<bool>,
    #[serde(rename = "manage_stock", skip_serializing_if = "Option::is_none")]
    pub manage_stock: Option<bool>,
    #[serde(rename = "is_free_shipping", skip_serializing_if = "Option::is_none")]
    pub is_free_shipping: Option<bool>,
    #[serde(rename = "seo_url", skip_serializing_if = "Option::is_none")]
    pub seo_url: Option<String>,
    #[serde(rename = "meta_title", skip_serializing_if = "Option::is_none")]
    pub meta_title: Option<String>,
    #[serde(rename = "meta_description", skip_serializing_if = "Option::is_none")]
    pub meta_description: Option<String>,
    #[serde(rename = "meta_keywords", skip_serializing_if = "Option::is_none")]
    pub meta_keywords: Option<Vec<String>>,
    /// If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    #[serde(rename = "categories_ids", skip_serializing_if = "Option::is_none")]
    pub categories_ids: Option<Vec<String>>,
    #[serde(rename = "stores_ids", skip_serializing_if = "Option::is_none")]
    pub stores_ids: Option<Vec<String>>,
    /// The passed items will completely replace the original items
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<models::ProductAddBatchPayloadInnerImagesInner>>,
    #[serde(rename = "product_images_ids", skip_serializing_if = "Option::is_none")]
    pub product_images_ids: Option<Vec<String>>,
    /// If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    #[serde(rename = "related_products_ids", skip_serializing_if = "Option::is_none")]
    pub related_products_ids: Option<Vec<String>>,
    /// If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    #[serde(rename = "up_sell_products_ids", skip_serializing_if = "Option::is_none")]
    pub up_sell_products_ids: Option<Vec<String>>,
    /// If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    #[serde(rename = "cross_sell_products_ids", skip_serializing_if = "Option::is_none")]
    pub cross_sell_products_ids: Option<Vec<String>>,
}

impl ProductVariantUpdateBatchPayloadInner {
    pub fn new(id: String, product_id: String) -> ProductVariantUpdateBatchPayloadInner {
        ProductVariantUpdateBatchPayloadInner {
            id,
            product_id,
            name: None,
            description: None,
            short_description: None,
            sku: None,
            upc: None,
            mpn: None,
            gtin: None,
            isbn: None,
            status: None,
            price: None,
            special_price: None,
            cost_price: None,
            retail_price: None,
            advanced_prices: None,
            quantity: None,
            reserve_quantity: None,
            increase_quantity: None,
            reduce_quantity: None,
            warehouse_id: None,
            manufacturer_id: None,
            weight: None,
            height: None,
            length: None,
            width: None,
            store_id: None,
            lang_id: None,
            tax_class_id: None,
            backorder_status: None,
            visible: None,
            is_default: None,
            in_stock: None,
            is_virtual: None,
            downloadable: None,
            manage_stock: None,
            is_free_shipping: None,
            seo_url: None,
            meta_title: None,
            meta_description: None,
            meta_keywords: None,
            categories_ids: None,
            stores_ids: None,
            images: None,
            product_images_ids: None,
            related_products_ids: None,
            up_sell_products_ids: None,
            cross_sell_products_ids: None,
        }
    }
}

