/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaxClassStates {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "tax", skip_serializing_if = "Option::is_none")]
    pub tax: Option<f64>,
    #[serde(rename = "tax_type", skip_serializing_if = "Option::is_none")]
    pub tax_type: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "zip_codes", skip_serializing_if = "Option::is_none")]
    pub zip_codes: Option<Vec<models::TaxClassZipCodes>>,
    #[serde(rename = "additional_fields", skip_serializing_if = "Option::is_none")]
    pub additional_fields: Option<serde_json::Value>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<serde_json::Value>,
}

impl TaxClassStates {
    pub fn new() -> TaxClassStates {
        TaxClassStates {
            id: None,
            tax: None,
            tax_type: None,
            name: None,
            code: None,
            zip_codes: None,
            additional_fields: None,
            custom_fields: None,
        }
    }
}

