/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookEvent {
    #[serde(rename = "webhook_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_name: Option<Option<String>>,
    #[serde(rename = "entity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub entity: Option<Option<String>>,
    #[serde(rename = "action", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub action: Option<Option<String>>,
    #[serde(rename = "filterable_fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filterable_fields: Option<Option<serde_json::Value>>,
    #[serde(rename = "additional_fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub additional_fields: Option<Option<serde_json::Value>>,
    #[serde(rename = "custom_fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Option<serde_json::Value>>,
}

impl WebhookEvent {
    pub fn new() -> WebhookEvent {
        WebhookEvent {
            webhook_name: None,
            entity: None,
            action: None,
            filterable_fields: None,
            additional_fields: None,
            custom_fields: None,
        }
    }
}

